include: package:lint/analysis_options.yaml

analyzer:
  exclude: 
    - lib/infrastructure/auth/*.g.dart
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
