name: team_inside
description: Team Inside

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.2
  cloud_firestore: ^3.1.8
  dartz: ^0.10.1
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.1
  get_it: ^7.2.0
  image_picker: ^0.8.4+8
  injectable: ^1.5.3
  ionicons: ^0.1.2
  json_annotation: ^4.4.0
  kt_dart: ^0.10.0
  uuid: ^3.0.5

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: null
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  json_serializable: ^6.1.4
  lint: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - lang/
    - assets/images/
